spring:
  datasource:
    url: jdbc:sqlite:./annotations.db
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 10000
      connection-timeout: 30000
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
        format_sql: true
        jdbc:
          time_zone: UTC

  jackson:
    default-property-inclusion: non_null

server:
  port: 8080
  tomcat:
    max-swallow-size: -1
    max-http-form-post-size: -1


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs
  disable-i18n: true

transcription:
  python-path: ${PYTHON_PATH}
  script-path: ${TRANSCRIBE_SCRIPT}

logging:
  level:
    root: INFO
    com.easy.annotations: DEBUG
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

gemini:
  api-url: https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent
  api-key: ${GEMINI_API_KEY:}
